# Generated by Django 4.1.7 on 2023-03-09 21:12

import ddam.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name_en', models.CharField(default='A Company that Makes Everything', help_text='Company, institute, site name (english version).', max_length=255, verbose_name='Organization Name (EN)')),
                ('organization_name_de', models.CharField(default='A Company that Makes Everything', help_text='Company, institute, site name (german version).', max_length=255, verbose_name='Organization Name (DE)')),
                ('organization_abbr', models.CharField(default='ACME', help_text='Company, institute, site abbreviation.', max_length=255, verbose_name='Abbreviation')),
                ('organization_street', models.CharField(blank=True, help_text='Street and house number. Used in printouts etc.', max_length=255)),
                ('organization_zip_code', models.CharField(blank=True, help_text='Used in printouts etc.', max_length=255, verbose_name='Organization ZIP Code')),
                ('organization_city', models.CharField(blank=True, help_text='Used in printouts etc.', max_length=255)),
                ('organization_url', models.URLField(blank=True, help_text='Used in printouts etc.', verbose_name='Organization URL')),
                ('organization_logo', models.FileField(blank=True, help_text='Logo file. SVG, transparent background', null=True, upload_to='branding/', validators=[ddam.organization.models.validate_logo_image_file_extension], verbose_name='Logo file')),
                ('organization_figurative_mark', models.FileField(blank=True, help_text='Bildmarke, quasi Logo ohne Wortmarke.', null=True, upload_to='branding/', validators=[ddam.organization.models.validate_logo_image_file_extension], verbose_name='Figurative Mark/Bildmarke')),
                ('organization_favicon', models.FileField(blank=True, null=True, upload_to='branding/', validators=[ddam.organization.models.validate_logo_image_file_extension], verbose_name='Favicon file')),
                ('documentation_url', models.URLField(blank=True, default='', help_text='If you host the documentation on your own, provide the URL here.')),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Branding',
            },
        ),
    ]
