# Generated by Django 4.1.7 on 2023-03-28 16:38

import ddam.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('updated_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='assets', validators=[ddam.core.validators.validate_fileextension, ddam.core.validators.validate_filetype, ddam.core.validators.validate_filesize])),
                ('filename_orig', models.CharField(editable=False, help_text='Original filename. Set automatically while creating an asset.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('with_costs', models.BooleanField(default=False, help_text='If you actually paid for this asset, set this info here.')),
                ('copyright_statement', models.CharField(blank=True, help_text='Appropriate credit/License holder (if required by license)', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Source/Origin of asset. Give an URL.', verbose_name='Source URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('updated_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('title', models.CharField(help_text='Name of dealer/distributor/vendor.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('updated_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('url', models.URLField(blank=True, help_text='URL of official license text.', null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('updated_by', models.EmailField(blank=True, editable=False, max_length=254)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, help_text='E.g. usage information, URLs')),
                ('media', models.CharField(choices=[('WEB', 'Web'), ('PRT', 'Print')], max_length=3)),
            ],
            options={
                'verbose_name': 'Usage',
                'verbose_name_plural': 'Usage',
            },
        ),
        migrations.CreateModel(
            name='UsageRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dealer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='dealer_title_unique_constraint'),
        ),
        migrations.AddField(
            model_name='asset',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dealer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.license'),
        ),
        migrations.AddField(
            model_name='asset',
            name='usage',
            field=models.ManyToManyField(blank=True, help_text='In which context this asset is in use.', to='core.usage', verbose_name='Usage'),
        ),
    ]
