# Generated by Django 4.1.7 on 2023-03-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsageRestriction',
        ),
        migrations.RemoveField(
            model_name='license',
            name='slug',
        ),
    ]
