# Generated by Django 4.1.7 on 2023-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usage',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
