# Generated by Django 4.1.7 on 2023-03-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_licence_slug_alter_usage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='filename_orig',
            field=models.CharField(default='bla', editable=False, help_text='Original filename. Set automatically while creating an asset.', max_length=255),
            preserve_default=False,
        ),
    ]
