# Generated by Django 4.1.7 on 2023-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asset_filename_orig'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source/Origin of asset. Give an URL.', verbose_name='Source URL'),
        ),
    ]
