# Generated by Django 4.1.7 on 2023-03-11 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of dealer/distributor/vendor.', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={'verbose_name': 'Usage', 'verbose_name_plural': 'Usage'},
        ),
        migrations.AddField(
            model_name='asset',
            name='with_costs',
            field=models.BooleanField(default=False, help_text='If you actually paid for this asset, set this info here.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usage',
            field=models.ManyToManyField(blank=True, help_text='In which context this asset is in use.', to='core.usage', verbose_name='Usage'),
        ),
        migrations.AddConstraint(
            model_name='dealer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='dealer_name_unique_constraint'),
        ),
        migrations.AddField(
            model_name='asset',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dealer'),
        ),
    ]
