# Generated by Django 4.1.7 on 2023-03-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dealer_alter_usage_options_asset_with_costs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='usage_restriction',
        ),
    ]
