# Generated by Django 4.1.7 on 2023-03-12 16:11

import ddam.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_asset_usage_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='assets/', validators=[ddam.core.validators.validate_fileextension, ddam.core.validators.validate_filetype, ddam.core.validators.validate_filesize]),
        ),
    ]
